//100 movies data
export const movies = [
  { id: 1, movieName: "KGF" },
  { id: 2, movieName: "KGF Chapter 2" },
  { id: 3, movieName: "RRR" },
  { id: 4, movieName: "OG" },
  { id: 5, movieName: "Brahmastra" },
  { id: 6, movieName: "Bahubali" },
  { id: 7, movieName: "Little Hearts" },
  { id: 8, movieName: "Hanuman" },
  { id: 9, movieName: "Gen V" },
  { id: 10, movieName: "The Boys" },
  { id: 11, movieName: "Inception" },
  { id: 12, movieName: "Interstellar" },
  { id: 13, movieName: "The Dark Knight" },
  { id: 14, movieName: "Pulp Fiction" },
  { id: 15, movieName: "Forrest Gump" },
  { id: 16, movieName: "The Matrix" },
  { id: 17, movieName: "Fight Club" },
  { id: 18, movieName: "The Shawshank Redemption" },
  { id: 19, movieName: "The Godfather" },
  { id: 20, movieName: "The Lord of the Rings" },
  { id: 21, movieName: "Star Wars" },
  { id: 22, movieName: "Avatar" },
  { id: 23, movieName: "Titanic" },
  { id: 24, movieName: "Gladiator" },
  { id: 25, movieName: "Jurassic Park" },
  { id: 26, movieName: "The Lion King" },
  { id: 27, movieName: "Toy Story" },
  { id: 28, movieName: "Finding Nemo" },
  { id: 29, movieName: "Up" },
  { id: 30, movieName: "Coco" },
  { id: 31, movieName: "Braveheart" },
  { id: 32, movieName: "The Avengers" },
  { id: 33, movieName: "Iron Man" },
  { id: 34, movieName: "Thor" },
  { id: 35, movieName: "Captain America" },
  { id: 36, movieName: "Black Panther" },
  { id: 37, movieName: "Doctor Strange" },
  { id: 38, movieName: "Spider-Man: Homecoming" },
  { id: 39, movieName: "Ant-Man" },
  { id: 40, movieName: "Guardians of the Galaxy" },
  { id: 41, movieName: "Deadpool" },
  { id: 42, movieName: "Logan" },
  { id: 43, movieName: "The Wolverine" },
  { id: 44, movieName: "X-Men: Days of Future Past" },
  { id: 45, movieName: "The Hunger Games" },
  { id: 46, movieName: "Divergent" },
  { id: 47, movieName: "Maze Runner" },
  { id: 48, movieName: "The Fault in Our Stars" },
  { id: 49, movieName: "La La Land" },
  { id: 50, movieName: "The Greatest Showman" },
  { id: 51, movieName: "A Star is Born" },
];
